logger:
  customLogger: null
  level: info
  logFile: false
  logFilePath: './logs/oas-tools.log'

errors:
  customErrorHandling: false

middleware:
  router:
    disable: false
    controllers: './controllers'
  validator:
    disable: false
    strict: false
  auth:
    disable: true
    grantsFile: null
  security:
    disable: true
    securityFile: null

docs:
  disable: false
  oasFile: '/oas-file'
  swaggerUi: '/docs'
